---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	task_planning_agent(task_planning_agent)
	recommend_outline_agent(recommend_outline_agent)
	slide_creating_agent(slide_creating_agent)
	slide_evaluating_agent(slide_evaluating_agent)
	end_node([end_node]):::last
	__start__ --> task_planning_agent;
	recommend_outline_agent --> slide_creating_agent;
	slide_creating_agent --> slide_evaluating_agent;
	slide_evaluating_agent --> task_planning_agent;
	task_planning_agent -.-> recommend_outline_agent;
	task_planning_agent -.-> slide_creating_agent;
	task_planning_agent -.-> end_node;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
