"""
PPTX Export Utilities

This module provides utilities for converting HTML slides to PPTX format
via PDF using ConvertAPI.
"""

import os
import logging
import tempfile
import zipfile
from datetime import datetime
from typing import List, Tuple, Optional

try:
    import convertapi
except ImportError:
    convertapi = None

logger = logging.getLogger(__name__)

class PPTXExportError(Exception):
    """Custom exception for PPTX export errors"""
    pass

def is_convertapi_available() -> bool:
    """Check if ConvertAPI is available and configured"""
    if convertapi is None:
        return False
    
    api_key = os.getenv('CONVERTAPI_API_KEY')
    return bool(api_key)

def setup_convertapi() -> bool:
    """Setup ConvertAPI with credentials"""
    try:
        api_key = os.getenv('CONVERTAPI_API_KEY')
        if not api_key:
            raise PPTXExportError("ConvertAPI key not configured")
        
        convertapi.api_credentials = api_key
        return True
    except Exception as e:
        logger.error(f"Failed to setup ConvertAPI: {str(e)}")
        return False

def convert_pdf_to_pptx(pdf_path: str, output_dir: str, base_filename: str) -> Tuple[bool, Optional[str], Optional[str]]:
    """
    Convert a PDF file to PPTX using ConvertAPI
    
    Args:
        pdf_path: Path to the PDF file
        output_dir: Directory to save the PPTX file
        base_filename: Base name for the output file (without extension)
    
    Returns:
        Tuple of (success: bool, pptx_path: str or None, error: str or None)
    """
    try:
        if not setup_convertapi():
            return False, None, "ConvertAPI not configured properly"
        
        if not os.path.exists(pdf_path):
            return False, None, f"PDF file not found: {pdf_path}"
        
        os.makedirs(output_dir, exist_ok=True)
        
        # Convert PDF to PPTX
        logger.info(f"Converting PDF to PPTX: {pdf_path}")
        result = convertapi.convert('pptx', {
            'File': pdf_path
        }, from_format='pdf')
        
        # Save PPTX to output directory
        result.save_files(output_dir)
        
        # Find the generated PPTX file (ConvertAPI may name it differently)
        pptx_files = [f for f in os.listdir(output_dir) if f.endswith('.pptx')]
        if not pptx_files:
            return False, None, "No PPTX file generated by ConvertAPI"
        
        # Get the most recently created PPTX file
        latest_pptx = max([os.path.join(output_dir, f) for f in pptx_files], key=os.path.getctime)
        
        # Rename to desired filename if needed
        desired_path = os.path.join(output_dir, f"{base_filename}.pptx")
        if latest_pptx != desired_path and not os.path.exists(desired_path):
            os.rename(latest_pptx, desired_path)
        elif os.path.exists(desired_path):
            # File already exists with correct name
            desired_path = latest_pptx
        
        logger.info(f"Successfully converted PDF to PPTX: {desired_path}")
        return True, desired_path, None
        
    except Exception as e:
        error_msg = str(e)
        logger.error(f"ConvertAPI error: {error_msg}")
        return False, None, error_msg

def convert_single_slide_to_pptx(slide_file: str, output_dir: str, slide_number: int) -> Tuple[bool, Optional[str], Optional[str]]:
    """
    Convert a single HTML slide to PPTX via PDF
    
    Args:
        slide_file: Path to the HTML slide file
        output_dir: Directory to save the PPTX file
        slide_number: Slide number for filename
    
    Returns:
        Tuple of (success: bool, pptx_path: str or None, error: str or None)
    """
    from .pdf_export import export_single_slide_to_pdf
    
    try:
        # Create temporary directory for PDF
        temp_dir = os.path.join(os.getcwd(), "temp")
        os.makedirs(temp_dir, exist_ok=True)
        
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        
        # Step 1: Export HTML slide to PDF
        temp_pdf_path = os.path.join(temp_dir, f"slide_{slide_number:03d}_{timestamp}.pdf")
        pdf_result = export_single_slide_to_pdf(slide_file, temp_pdf_path)
        
        if not pdf_result["success"]:
            return False, None, f"Failed to create PDF: {pdf_result['error']}"
        
        # Step 2: Convert PDF to PPTX
        base_filename = f"slide_{slide_number:03d}_{timestamp}"
        success, pptx_path, error = convert_pdf_to_pptx(temp_pdf_path, output_dir, base_filename)
        
        # Clean up temporary PDF
        if os.path.exists(temp_pdf_path):
            os.remove(temp_pdf_path)
        
        return success, pptx_path, error
        
    except Exception as e:
        # Clean up on error
        if 'temp_pdf_path' in locals() and os.path.exists(temp_pdf_path):
            try:
                os.remove(temp_pdf_path)
            except:
                pass
        
        return False, None, str(e)

def convert_multiple_slides_to_pptx(slide_files: List[str], output_dir: str, base_filename: str, combine: bool = True) -> Tuple[bool, Optional[str], Optional[str]]:
    """
    Convert multiple HTML slides to PPTX
    
    Args:
        slide_files: List of HTML slide file paths
        output_dir: Directory to save the PPTX file(s)
        base_filename: Base name for the output file
        combine: If True, combine all slides into one PPTX; if False, create individual PPTX files
    
    Returns:
        Tuple of (success: bool, result_path: str or None, error: str or None)
        result_path will be a single PPTX file if combine=True, or a ZIP file if combine=False
    """
    from .pdf_export import export_slides_to_pdf, export_single_slide_to_pdf
    
    try:
        temp_dir = os.path.join(os.getcwd(), "temp")
        os.makedirs(temp_dir, exist_ok=True)
        
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        
        if combine:
            # Combine all slides into one PPTX
            temp_pdf_path = os.path.join(temp_dir, f"{base_filename}_{timestamp}.pdf")
            pdf_result = export_slides_to_pdf(slide_files, temp_pdf_path, method="auto", combine=True)
            
            if not pdf_result["success"]:
                return False, None, f"Failed to create combined PDF: {pdf_result['error']}"
            
            # Convert combined PDF to PPTX
            final_filename = f"{base_filename}_{timestamp}"
            success, pptx_path, error = convert_pdf_to_pptx(temp_pdf_path, output_dir, final_filename)
            
            # Clean up temporary PDF
            if os.path.exists(temp_pdf_path):
                os.remove(temp_pdf_path)
            
            return success, pptx_path, error
        
        else:
            # Create individual PPTX files and ZIP them
            with tempfile.TemporaryDirectory() as temp_pptx_dir:
                pptx_files = []
                
                for i, slide_file in enumerate(slide_files, 1):
                    try:
                        # Export individual slide to PDF
                        slide_name = os.path.splitext(os.path.basename(slide_file))[0]
                        temp_pdf_path = os.path.join(temp_dir, f"{slide_name}_{timestamp}.pdf")
                        
                        pdf_result = export_single_slide_to_pdf(slide_file, temp_pdf_path)
                        if not pdf_result["success"]:
                            logger.warning(f"Failed to create PDF for slide {i}: {pdf_result['error']}")
                            continue
                        
                        # Convert PDF to PPTX
                        success, pptx_path, error = convert_pdf_to_pptx(temp_pdf_path, temp_pptx_dir, slide_name)
                        
                        # Clean up temp PDF
                        if os.path.exists(temp_pdf_path):
                            os.remove(temp_pdf_path)
                        
                        if success and pptx_path:
                            pptx_files.append((pptx_path, f"{slide_name}.pptx"))
                            logger.info(f"Converted slide {i} to PPTX successfully")
                        else:
                            logger.warning(f"Failed to convert slide {i} to PPTX: {error}")
                            
                    except Exception as e:
                        logger.warning(f"Error converting slide {i}: {str(e)}")
                        continue
                
                if not pptx_files:
                    return False, None, "No slides could be converted to PPTX"
                
                # Create ZIP file with all PPTX files
                zip_filename = f"{base_filename}_individual_{timestamp}.zip"
                zip_path = os.path.join(output_dir, zip_filename)
                
                with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zip_file:
                    for pptx_path, pptx_filename in pptx_files:
                        zip_file.write(pptx_path, pptx_filename)
                
                logger.info(f"Successfully created ZIP with {len(pptx_files)} individual PPTX files")
                return True, zip_path, None
        
    except Exception as e:
        return False, None, str(e)

def get_pptx_export_info() -> dict:
    """
    Get information about PPTX export capabilities
    
    Returns:
        Dictionary with export information
    """
    return {
        "available": is_convertapi_available(),
        "convertapi_installed": convertapi is not None,
        "api_key_configured": bool(os.getenv('CONVERTAPI_API_KEY')),
        "supported_formats": ["single_slide", "all_slides"],
        "requirements": {
            "convertapi_package": convertapi is not None,
            "api_key": bool(os.getenv('CONVERTAPI_API_KEY'))
        }
    } 