from pydantic import BaseModel, Field
from typing import List, Optional

class SearchQueryList(BaseModel):
    query: List[str] = Field(
        description="A list of search queries to be used for web research."
    )
    rationale: str = Field(
        description="A brief explanation of why these queries are relevant to the research topic."
    )
    
class Task(BaseModel):
    id: str = Field(description="Unique identifier for the task.")
    description: str = Field(description="A concise description of what this task aims to achieve.")


class Plan(BaseModel):
    tasks: List[Task] = Field(description="A list of tasks to be executed.")
    
    
# New structured schemas for improved workflow
class SlideStructure(BaseModel):
    """Individual slide with title, content, and optional layout instructions"""
    slide_number: int = Field(description="The number/position of the slide (1, 2, 3, etc.)")
    title: str = Field(description="The main title/heading of the slide")
    content: str = Field(description="The main content/body text of the slide")
    layout_instructions: Optional[str] = Field(default=None, description="Layout and design instructions for this specific slide")

class StructuredOutline(BaseModel):
    """Complete presentation outline with structured slides"""
    presentation_title: str = Field(description="The overall title of the presentation")
    slides: List[SlideStructure] = Field(description="List of all slides in the presentation")
    
class LayoutInstructions(BaseModel):
    """Layout instructions for each slide generated by artist agent"""
    slide_layouts: List[SlideStructure] = Field(description="List of slides with updated layout instructions")

class ColorPalette(BaseModel):
    """Color palette for presentation slides"""
    primary: str = Field(description="Primary color for main elements (hex code like #FF5733)")
    secondary: str = Field(description="Secondary color for supporting elements (hex code)")
    accent: str = Field(description="Accent color for highlights and call-to-action elements (hex code)")
    background: str = Field(description="Background color for slides (hex code)")
    text: str = Field(description="Main text color for readability (hex code)")
    
class CoverSlideResponse(BaseModel):
    """Response structure for cover slide generation"""
    html_content: str = Field(description="Complete HTML content for the cover slide")
    color_palette: ColorPalette = Field(description="Extracted color palette from the cover slide")
    topic: str = Field(description="The presentation topic this cover slide was created for")

# Legacy schemas (keep for backward compatibility)
class Slide_Content(BaseModel):
    slide_number: int = Field(description="The number of the slide.")
    slide_title: str = Field(description="The title of the slide.")
    slide_body: str = Field(description="All other content of the slide.")
    slide_script: str = Field(description="The script of the slide for user to read.")
    
class Outline(BaseModel):
    outline: List[Slide_Content] = Field(description="A list of slide content to be used to generate the outline.")